#ifndef URN_JAUS_JSS_ENVIRONMENTSENSING_VISUALSENSOR_1_0_INTERNALEVENTSSET
#define URN_JAUS_JSS_ENVIRONMENTSENSING_VISUALSENSOR_1_0_INTERNALEVENTSSET

#include "BroadcastGlobal.h"
#include "BroadcastLocal.h"
#include "EventError.h"
#include "EventOccurred.h"
#include "Timeout.h"

#endif //URN_JAUS_JSS_ENVIRONMENTSENSING_VISUALSENSOR_1_0_INTERNALEVENTSSET
