/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : LocalWaypointListDriver_SendFSM_sm.sm
 */

#include "urn_jaus_jss_mobility_LocalWaypointListDriver_1_0/Messages/MessageSet.h"
#include "urn_jaus_jss_mobility_LocalWaypointListDriver_1_0/LocalWaypointListDriver_SendFSM.h"
#include "include/urn_jaus_jss_mobility_LocalWaypointListDriver_1_0/LocalWaypointListDriver_SendFSM_sm.h"

using namespace statemap;

namespace urn_jaus_jss_mobility_LocalWaypointListDriver_1_0
{
    // Static class declarations.
    LocalWaypointListDriver_SendFSM_SM_Sending LocalWaypointListDriver_SendFSM_SM::Sending("LocalWaypointListDriver_SendFSM_SM::Sending", 0);
    LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE("LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE", 1);

    void LocalWaypointListDriver_SendFSMState::BroadcastGlobalTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::BroadcastLocalTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::CancelEventTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::ClearEmergencyTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::CreateEventTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::DeleteElementTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::EventErrorTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::EventOccurredTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::ExecuteListTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::FailureTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::InitializedTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::QueryActiveElementTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::QueryAuthorityTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::QueryControlTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::QueryElementCountTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::QueryElementListTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::QueryElementTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::QueryEventsTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::QueryLocalWaypointTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::QueryStatusTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::QueryTimeoutTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::QueryTravelSpeedTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::ReceiveTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::ReleaseControlTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::RequestControlTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::ResetTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::ResumeTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::SendTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::SetAuthorityTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::SetElementTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::SetEmergencyTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::ShutdownTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::StandbyTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::TimeoutTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::UpdateEventTransition(LocalWaypointListDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void LocalWaypointListDriver_SendFSMState::Default(LocalWaypointListDriver_SendFSMContext& context)
    {
        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Default"
                << std::endl;
        }

        throw (
            TransitionUndefinedException(
                context.getState().getName(),
                context.getTransition()));

        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::BroadcastGlobalTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastGlobalTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastGlobalTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::BroadcastLocalTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastLocalTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastLocalTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::CancelEventTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::CancelEventTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::CancelEventTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::ClearEmergencyTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ClearEmergencyTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ClearEmergencyTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::CreateEventTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::CreateEventTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::CreateEventTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::DeleteElementTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::DeleteElementTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::DeleteElementTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::EventErrorTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::EventErrorTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::EventErrorTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::EventOccurredTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::EventOccurredTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::EventOccurredTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::ExecuteListTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ExecuteListTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ExecuteListTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::FailureTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::FailureTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::FailureTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::InitializedTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::InitializedTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::InitializedTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryActiveElementTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryActiveElementTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryActiveElementTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryAuthorityTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryAuthorityTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryAuthorityTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryControlTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryControlTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryControlTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryElementCountTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryElementCountTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryElementCountTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryElementListTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryElementListTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryElementListTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryElementTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryElementTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryElementTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryEventsTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryEventsTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryEventsTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryLocalWaypointTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryLocalWaypointTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryLocalWaypointTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryStatusTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryStatusTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryStatusTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryTimeoutTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryTimeoutTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryTimeoutTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryTravelSpeedTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryTravelSpeedTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryTravelSpeedTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::ReceiveTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ReceiveTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ReceiveTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::ReleaseControlTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ReleaseControlTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ReleaseControlTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::RequestControlTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::RequestControlTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::RequestControlTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::ResetTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ResetTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ResetTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::ResumeTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ResumeTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ResumeTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::SendTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::SendTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::SendTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::SetAuthorityTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::SetAuthorityTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::SetAuthorityTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::SetElementTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::SetElementTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::SetElementTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::SetEmergencyTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::SetEmergencyTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::SetEmergencyTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::ShutdownTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ShutdownTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ShutdownTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::StandbyTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::StandbyTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::StandbyTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::TimeoutTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::TimeoutTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::TimeoutTransition()"
                << std::endl;
        }


        return;
    }

    void LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::UpdateEventTransition(LocalWaypointListDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::UpdateEventTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::UpdateEventTransition()"
                << std::endl;
        }


        return;
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
