/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : Management_SendFSM.sm
 */

#include "urn_jaus_jss_core_Management_1_1/Messages/MessageSet.h"
#include "urn_jaus_jss_core_Management_1_1/Management_SendFSM.h"
#include "include/urn_jaus_jss_core_Management_1_1/Management_SendFSM_sm.h"

using namespace statemap;

namespace urn_jaus_jss_core_Management_1_1
{
    // Static class declarations.
    Management_SendFSM_SM_Sending Management_SendFSM_SM::Sending("Management_SendFSM_SM::Sending", 0);
    Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE Management_SendFSM_SM::Internally_Generated_State_DO_NOT_USE("Management_SendFSM_SM::Internally_Generated_State_DO_NOT_USE", 1);

    void Management_SendFSMState::BroadcastGlobalTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::BroadcastLocalTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::CancelEventTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::ClearEmergencyTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::CommandCompletedTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::CommandExpiredTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::CreateCommandEventTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::CreateEvntTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::EventErrorTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::EventOccurredTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::FailureTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::InitializedTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::QueryAuthorityTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::QueryControlTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::QueryEventTimeoutTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::QueryEventsTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::QueryStatusTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::QueryTimeoutTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::ReceiveTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::ReleaseControlTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::RequestControlTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::ResetTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::ResumeTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::SendTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::SetAuthorityTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::SetEmergencyTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::ShutdownTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::StandbyTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::TimeoutTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::UpdateEventTransition(Management_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Management_SendFSMState::Default(Management_SendFSMContext& context)
    {
        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Default"
                << std::endl;
        }

        throw (
            TransitionUndefinedException(
                context.getState().getName(),
                context.getTransition()));

        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::BroadcastGlobalTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM BroadcastGlobalTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::BroadcastLocalTransition(Management_SendFSMContext& context)
        {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM BroadcastLocalTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::CancelEventTransition(Management_SendFSMContext& context)
        {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM CancelEventTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::ClearEmergencyTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM ClearEmergencyTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::CommandCompletedTransition(Management_SendFSMContext& context)
        {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM CommandCompletedTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::CommandExpiredTransition(Management_SendFSMContext& context)
        {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM CommandExpiredTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::CreateCommandEventTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM CreateCommandEventTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::CreateEvntTransition(Management_SendFSMContext& context)
        {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM CreateEvntTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::EventErrorTransition(Management_SendFSMContext& context)
        {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM EventErrorTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::EventOccurredTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM EventOccurredTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::FailureTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM FailureTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::InitializedTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM InitializedTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryAuthorityTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM QueryAuthorityTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryControlTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM QueryControlTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryEventTimeoutTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM QueryEventTimeoutTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryEventsTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM QueryEventsTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryStatusTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM QueryStatusTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryTimeoutTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM QueryTimeoutTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::ReceiveTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM ReceiveTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::ReleaseControlTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM ReleaseControlTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::RequestControlTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM RequestControlTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::ResetTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM ResetTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::ResumeTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM ResumeTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::SendTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM SendTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::SetAuthorityTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM SetAuthorityTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::SetEmergencyTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM SetEmergencyTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::ShutdownTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM ShutdownTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::StandbyTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM StandbyTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::TimeoutTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM TimeoutTransition()"
                << std::endl;
        }


        return;
    }

    void Management_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::UpdateEventTransition(Management_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Management_SendFSM_SM UpdateEventTransition()"
                << std::endl;
        }


        return;
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
