/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : Events_ReceiveFSM.sm
 */

package src.urn_jaus_jss_core_Events_1_1;

import framework.internalEvents.*;
import src.urn_jaus_jss_core_Events_1_1.InternalEvents.*;
import src.urn_jaus_jss_core_Events_1_1.Messages.*;
import java.io.PrintStream;

public class Events_ReceiveFSMContext
    extends statemap.FSMContext
{
//---------------------------------------------------------------
// Member methods.
//

    public Events_ReceiveFSMContext(Events_ReceiveFSM owner)
    {
        super (Events_ReceiveFSM_SM.Receiving_Ready);

        _owner = owner;
    }

    public Events_ReceiveFSMContext(Events_ReceiveFSM owner, Events_ReceiveFSMState initState)
    {
        super (initState);

        _owner = owner;
    }

    public void enterStartState()
    {
        getState().Entry(this);
        return;
    }

    public void BroadcastGlobalTransition()
    {
        _transition = "BroadcastGlobalTransition";
        getState().BroadcastGlobalTransition(this);
        _transition = "";
        return;
    }

    public void BroadcastLocalTransition()
    {
        _transition = "BroadcastLocalTransition";
        getState().BroadcastLocalTransition(this);
        _transition = "";
        return;
    }

    public void CancelEventTransition()
    {
        _transition = "CancelEventTransition";
        getState().CancelEventTransition(this);
        _transition = "";
        return;
    }

    public void CommandCompletedTransition()
    {
        _transition = "CommandCompletedTransition";
        getState().CommandCompletedTransition(this);
        _transition = "";
        return;
    }

    public void CommandExpiredTransition()
    {
        _transition = "CommandExpiredTransition";
        getState().CommandExpiredTransition(this);
        _transition = "";
        return;
    }

    public void CreateCommandEventTransition()
    {
        _transition = "CreateCommandEventTransition";
        getState().CreateCommandEventTransition(this);
        _transition = "";
        return;
    }

    public void CreateEventTransition()
    {
        _transition = "CreateEventTransition";
        getState().CreateEventTransition(this);
        _transition = "";
        return;
    }

    public void EventErrorTransition()
    {
        _transition = "EventErrorTransition";
        getState().EventErrorTransition(this);
        _transition = "";
        return;
    }

    public void EventOccurredTransition()
    {
        _transition = "EventOccurredTransition";
        getState().EventOccurredTransition(this);
        _transition = "";
        return;
    }

    public void QueryEventTimeoutTransition()
    {
        _transition = "QueryEventTimeoutTransition";
        getState().QueryEventTimeoutTransition(this);
        _transition = "";
        return;
    }

    public void QueryEventsTransition()
    {
        _transition = "QueryEventsTransition";
        getState().QueryEventsTransition(this);
        _transition = "";
        return;
    }

    public void ReceiveTransition()
    {
        _transition = "ReceiveTransition";
        getState().ReceiveTransition(this);
        _transition = "";
        return;
    }

    public void ReceiveTransition(CancelEvent msg, Receive.Body.ReceiveRec transportData)
    {
        _transition = "ReceiveTransition";
        getState().ReceiveTransition(this, msg, transportData);
        _transition = "";
        return;
    }

    public void ReceiveTransition(CreateEvent msg, Receive.Body.ReceiveRec transportData)
    {
        _transition = "ReceiveTransition";
        getState().ReceiveTransition(this, msg, transportData);
        _transition = "";
        return;
    }

    public void ReceiveTransition(QueryEventTimeout msg, Receive.Body.ReceiveRec transportData)
    {
        _transition = "ReceiveTransition";
        getState().ReceiveTransition(this, msg, transportData);
        _transition = "";
        return;
    }

    public void ReceiveTransition(QueryEvents msg, Receive.Body.ReceiveRec transportData)
    {
        _transition = "ReceiveTransition";
        getState().ReceiveTransition(this, msg, transportData);
        _transition = "";
        return;
    }

    public void ReceiveTransition(UpdateEvent msg, Receive.Body.ReceiveRec transportData)
    {
        _transition = "ReceiveTransition";
        getState().ReceiveTransition(this, msg, transportData);
        _transition = "";
        return;
    }

    public void SendTransition()
    {
        _transition = "SendTransition";
        getState().SendTransition(this);
        _transition = "";
        return;
    }

    public void TimeoutTransition()
    {
        _transition = "TimeoutTransition";
        getState().TimeoutTransition(this);
        _transition = "";
        return;
    }

    public void UpdateEventTransition()
    {
        _transition = "UpdateEventTransition";
        getState().UpdateEventTransition(this);
        _transition = "";
        return;
    }

    public Events_ReceiveFSMState getState()
        throws statemap.StateUndefinedException
    {
        if (_state == null)
        {
            throw(
                new statemap.StateUndefinedException());
        }

        return ((Events_ReceiveFSMState) _state);
    }

    protected Events_ReceiveFSM getOwner()
    {
        return (_owner);
    }

    public void setOwner(Events_ReceiveFSM owner)
    {
        if (owner == null)
        {
            throw (
                new NullPointerException(
                    "null owner"));
        }
        else
        {
            _owner = owner;
        }

        return;
    }

//---------------------------------------------------------------
// Member data.
//

    transient private Events_ReceiveFSM _owner;

//---------------------------------------------------------------
// Inner classes.
//

    public static abstract class Events_ReceiveFSMState
        extends statemap.State
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected Events_ReceiveFSMState(String name, int id)
        {
            super (name, id);
        }

        protected void Entry(Events_ReceiveFSMContext context) {}
        protected void Exit(Events_ReceiveFSMContext context) {}

        protected void BroadcastGlobalTransition(Events_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void BroadcastLocalTransition(Events_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void CancelEventTransition(Events_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void CommandCompletedTransition(Events_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void CommandExpiredTransition(Events_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void CreateCommandEventTransition(Events_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void CreateEventTransition(Events_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void EventErrorTransition(Events_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void EventOccurredTransition(Events_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void QueryEventTimeoutTransition(Events_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void QueryEventsTransition(Events_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void ReceiveTransition(Events_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void ReceiveTransition(Events_ReceiveFSMContext context, CancelEvent msg, Receive.Body.ReceiveRec transportData)
        {
            Default(context);
        }

        protected void ReceiveTransition(Events_ReceiveFSMContext context, CreateEvent msg, Receive.Body.ReceiveRec transportData)
        {
            Default(context);
        }

        protected void ReceiveTransition(Events_ReceiveFSMContext context, QueryEventTimeout msg, Receive.Body.ReceiveRec transportData)
        {
            Default(context);
        }

        protected void ReceiveTransition(Events_ReceiveFSMContext context, QueryEvents msg, Receive.Body.ReceiveRec transportData)
        {
            Default(context);
        }

        protected void ReceiveTransition(Events_ReceiveFSMContext context, UpdateEvent msg, Receive.Body.ReceiveRec transportData)
        {
            Default(context);
        }

        protected void SendTransition(Events_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void TimeoutTransition(Events_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void UpdateEventTransition(Events_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void Default(Events_ReceiveFSMContext context)
        {
            if (context.getDebugFlag() == true)
            {
                PrintStream str = 
                    context.getDebugStream();

                str.println(
                    "TRANSITION   : Default");
            }

            throw (
                new statemap.TransitionUndefinedException(
                    "State: " +
                    context.getState().getName() +
                    ", Transition: " +
                    context.getTransition()));
        }

    //-----------------------------------------------------------
    // Member data.
    //
    }

    /* package */ static abstract class Events_ReceiveFSM_SM
    {
    //-----------------------------------------------------------
    // Member methods.
    //

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
        // Constants.
        //
        public static final Events_ReceiveFSM_SM_Default.Events_ReceiveFSM_SM_Receiving_Ready Receiving_Ready =
            new Events_ReceiveFSM_SM_Default.Events_ReceiveFSM_SM_Receiving_Ready("Events_ReceiveFSM_SM.Receiving_Ready", 0);
        public static final Events_ReceiveFSM_SM_Default.Events_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE Internally_Generated_State_DO_NOT_USE =
            new Events_ReceiveFSM_SM_Default.Events_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE("Events_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE", 1);
        private static final Events_ReceiveFSM_SM_Default Default =
            new Events_ReceiveFSM_SM_Default("Events_ReceiveFSM_SM.Default", -1);

    }

    protected static class Events_ReceiveFSM_SM_Default
        extends Events_ReceiveFSMState
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected Events_ReceiveFSM_SM_Default(String name, int id)
        {
            super (name, id);
        }

    //-----------------------------------------------------------
    // Inner classse.
    //


        private static final class Events_ReceiveFSM_SM_Receiving_Ready
            extends Events_ReceiveFSM_SM_Default
        {
        //-------------------------------------------------------
        // Member methods.
        //

            private Events_ReceiveFSM_SM_Receiving_Ready(String name, int id)
            {
                super (name, id);
            }

            protected void EventErrorTransition(Events_ReceiveFSMContext context)
            {
                Events_ReceiveFSM ctxt = context.getOwner();

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Receiving_Ready.EventErrorTransition()");
                }

                if (ctxt.eventExists())
                {
                    Events_ReceiveFSMState endState = context.getState();

                    context.clearState();
                    try
                    {
                        ctxt.sendRejectEventRequestAction();
                    }
                    finally
                    {
                        context.setState(endState);
                    }
                }
                else
                {
                    super.EventErrorTransition(context);
                }

                return;
            }

            protected void EventOccurredTransition(Events_ReceiveFSMContext context)
            {
                Events_ReceiveFSM ctxt = context.getOwner();

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Receiving_Ready.EventOccurredTransition()");
                }

                if (ctxt.eventExists())
                {
                    Events_ReceiveFSMState endState = context.getState();

                    context.clearState();
                    try
                    {
                        ctxt.sendEventAction();
                    }
                    finally
                    {
                        context.setState(endState);
                    }
                }
                else
                {
                    super.EventOccurredTransition(context);
                }

                return;
            }

            protected void ReceiveTransition(Events_ReceiveFSMContext context, CancelEvent msg, Receive.Body.ReceiveRec transportData)
            {
                Events_ReceiveFSM ctxt = context.getOwner();

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Receiving_Ready.ReceiveTransition(CancelEvent msg, Receive.Body.ReceiveRec transportData)");
                }

                if (! ctxt.eventExists(msg))
                {
                    Events_ReceiveFSMState endState = context.getState();

                    context.clearState();
                    try
                    {
                        ctxt.SendAction("RejectEventRequest", msg, transportData);
                    }
                    finally
                    {
                        context.setState(endState);
                    }
                }
                else if (ctxt.eventExists(msg))
                {
                    Events_ReceiveFSMState endState = context.getState();

                    context.clearState();
                    try
                    {
                        ctxt.cancelEventAction(msg);
                        ctxt.SendAction("ConfirmEventRequest", msg, transportData);
                        ctxt.stopEventTimerAction();
                    }
                    finally
                    {
                        context.setState(endState);
                    }
                }                else
                {
                    super.ReceiveTransition(context, msg, transportData);
                }

                return;
            }

            protected void ReceiveTransition(Events_ReceiveFSMContext context, CreateEvent msg, Receive.Body.ReceiveRec transportData)
            {
                Events_ReceiveFSM ctxt = context.getOwner();

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Receiving_Ready.ReceiveTransition(CreateEvent msg, Receive.Body.ReceiveRec transportData)");
                }

                if (ctxt.isSupported(msg) && ! ctxt.eventExists(msg))
                {
                    Events_ReceiveFSMState endState = context.getState();

                    context.clearState();
                    try
                    {
                        ctxt.createEventAction(msg);
                        ctxt.SendAction("ConfirmEventRequest", msg, transportData);
                        ctxt.resetEventTimerAction();
                    }
                    finally
                    {
                        context.setState(endState);
                    }
                }
                else if (ctxt.isSupported(msg) && ctxt.eventExists(msg))
                {
                    Events_ReceiveFSMState endState = context.getState();

                    context.clearState();
                    try
                    {
                        ctxt.updateEventAction(msg);
                        ctxt.SendAction("ConfirmEventRequest", msg, transportData);
                        ctxt.resetEventTimerAction();
                    }
                    finally
                    {
                        context.setState(endState);
                    }
                }
                else if (! ctxt.isSupported(msg))
                {
                    Events_ReceiveFSMState endState = context.getState();

                    context.clearState();
                    try
                    {
                        ctxt.SendAction("RejectEventRequest", msg, transportData);
                    }
                    finally
                    {
                        context.setState(endState);
                    }
                }                else
                {
                    super.ReceiveTransition(context, msg, transportData);
                }

                return;
            }

            protected void ReceiveTransition(Events_ReceiveFSMContext context, QueryEventTimeout msg, Receive.Body.ReceiveRec transportData)
            {
                Events_ReceiveFSM ctxt = context.getOwner();

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Receiving_Ready.ReceiveTransition(QueryEventTimeout msg, Receive.Body.ReceiveRec transportData)");
                }

                Events_ReceiveFSMState endState = context.getState();

                context.clearState();
                try
                {
                    ctxt.SendAction("ReportEventTimeout", msg, transportData);
                }
                finally
                {
                    context.setState(endState);
                }
                return;
            }

            protected void ReceiveTransition(Events_ReceiveFSMContext context, QueryEvents msg, Receive.Body.ReceiveRec transportData)
            {
                Events_ReceiveFSM ctxt = context.getOwner();

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Receiving_Ready.ReceiveTransition(QueryEvents msg, Receive.Body.ReceiveRec transportData)");
                }

                Events_ReceiveFSMState endState = context.getState();

                context.clearState();
                try
                {
                    ctxt.SendAction("ReportEvents", msg, transportData);
                }
                finally
                {
                    context.setState(endState);
                }
                return;
            }

            protected void ReceiveTransition(Events_ReceiveFSMContext context, UpdateEvent msg, Receive.Body.ReceiveRec transportData)
            {
                Events_ReceiveFSM ctxt = context.getOwner();

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Receiving_Ready.ReceiveTransition(UpdateEvent msg, Receive.Body.ReceiveRec transportData)");
                }

                if (ctxt.isSupported(msg) && ctxt.eventExists(msg))
                {
                    Events_ReceiveFSMState endState = context.getState();

                    context.clearState();
                    try
                    {
                        ctxt.updateEventAction(msg);
                        ctxt.SendAction("ConfirmEventRequest", msg, transportData);
                        ctxt.resetEventTimerAction();
                    }
                    finally
                    {
                        context.setState(endState);
                    }
                }
                else if (! ctxt.isSupported(msg) || ! ctxt.eventExists(msg))
                {
                    Events_ReceiveFSMState endState = context.getState();

                    context.clearState();
                    try
                    {
                        ctxt.SendAction("RejectEventRequest", msg, transportData);
                    }
                    finally
                    {
                        context.setState(endState);
                    }
                }                else
                {
                    super.ReceiveTransition(context, msg, transportData);
                }

                return;
            }

            protected void TimeoutTransition(Events_ReceiveFSMContext context)
            {
                Events_ReceiveFSM ctxt = context.getOwner();

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Receiving_Ready.TimeoutTransition()");
                }

                Events_ReceiveFSMState endState = context.getState();

                context.clearState();
                try
                {
                    ctxt.cancelEventAction();
                    ctxt.SendAction("ConfirmEventRequest");
                    ctxt.stopEventTimerAction();
                }
                finally
                {
                    context.setState(endState);
                }
                return;
            }

        //-------------------------------------------------------
        // Member data.
        //
        }

        private static final class Events_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE
            extends Events_ReceiveFSM_SM_Default
        {
        //-------------------------------------------------------
        // Member methods.
        //

            private Events_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE(String name, int id)
            {
                super (name, id);
            }

            protected void BroadcastGlobalTransition(Events_ReceiveFSMContext context)
            {

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.BroadcastGlobalTransition()");
                }


                return;
            }

            protected void BroadcastLocalTransition(Events_ReceiveFSMContext context)
            {

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.BroadcastLocalTransition()");
                }


                return;
            }

            protected void CancelEventTransition(Events_ReceiveFSMContext context)
            {

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.CancelEventTransition()");
                }


                return;
            }

            protected void CommandCompletedTransition(Events_ReceiveFSMContext context)
            {

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.CommandCompletedTransition()");
                }


                return;
            }

            protected void CommandExpiredTransition(Events_ReceiveFSMContext context)
            {

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.CommandExpiredTransition()");
                }


                return;
            }

            protected void CreateCommandEventTransition(Events_ReceiveFSMContext context)
            {

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.CreateCommandEventTransition()");
                }


                return;
            }

            protected void CreateEventTransition(Events_ReceiveFSMContext context)
            {

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.CreateEventTransition()");
                }


                return;
            }

            protected void EventErrorTransition(Events_ReceiveFSMContext context)
            {

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.EventErrorTransition()");
                }


                return;
            }

            protected void EventOccurredTransition(Events_ReceiveFSMContext context)
            {

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.EventOccurredTransition()");
                }


                return;
            }

            protected void QueryEventTimeoutTransition(Events_ReceiveFSMContext context)
            {

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryEventTimeoutTransition()");
                }


                return;
            }

            protected void QueryEventsTransition(Events_ReceiveFSMContext context)
            {

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryEventsTransition()");
                }


                return;
            }

            protected void ReceiveTransition(Events_ReceiveFSMContext context)
            {

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.ReceiveTransition()");
                }


                return;
            }

            protected void SendTransition(Events_ReceiveFSMContext context)
            {

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.SendTransition()");
                }


                return;
            }

            protected void TimeoutTransition(Events_ReceiveFSMContext context)
            {

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.TimeoutTransition()");
                }


                return;
            }

            protected void UpdateEventTransition(Events_ReceiveFSMContext context)
            {

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("TRANSITION   : Events_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.UpdateEventTransition()");
                }


                return;
            }

        //-------------------------------------------------------
        // Member data.
        //
        }

    //-----------------------------------------------------------
    // Member data.
    //
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
