#ifndef _H_LISTMANAGER_SENDFSM_SM
#define _H_LISTMANAGER_SENDFSM_SM

/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : ListManager_SendFSM_sm.sm
 */


#define SMC_USES_IOSTREAMS

#include <statemap.h>

namespace urn_jaus_jss_mobility_ListManager_1_0
{
    // Forward declarations.
    class ListManager_SendFSM_SM;
    class ListManager_SendFSM_SM_Sending;
    class ListManager_SendFSM_SM_Internally_Generated_State_DO_NOT_USE;
    class ListManager_SendFSM_SM_Default;
    class ListManager_SendFSMState;
    class ListManager_SendFSMContext;
    class ListManager_SendFSM;

    class ListManager_SendFSMState :
        public statemap::State
    {
    public:

        ListManager_SendFSMState(const char *name, int stateId)
        : statemap::State(name, stateId)
        {};

        virtual void Entry(ListManager_SendFSMContext&) {};
        virtual void Exit(ListManager_SendFSMContext&) {};

        virtual void BroadcastGlobalTransition(ListManager_SendFSMContext& context);
        virtual void BroadcastLocalTransition(ListManager_SendFSMContext& context);
        virtual void CancelEventTransition(ListManager_SendFSMContext& context);
        virtual void ClearEmergencyTransition(ListManager_SendFSMContext& context);
        virtual void CreateEventTransition(ListManager_SendFSMContext& context);
        virtual void DeleteElementTransition(ListManager_SendFSMContext& context);
        virtual void EventErrorTransition(ListManager_SendFSMContext& context);
        virtual void EventOccurredTransition(ListManager_SendFSMContext& context);
        virtual void FailureTransition(ListManager_SendFSMContext& context);
        virtual void InitializedTransition(ListManager_SendFSMContext& context);
        virtual void QueryAuthorityTransition(ListManager_SendFSMContext& context);
        virtual void QueryControlTransition(ListManager_SendFSMContext& context);
        virtual void QueryElementCountTransition(ListManager_SendFSMContext& context);
        virtual void QueryElementListTransition(ListManager_SendFSMContext& context);
        virtual void QueryElementTransition(ListManager_SendFSMContext& context);
        virtual void QueryEventsTransition(ListManager_SendFSMContext& context);
        virtual void QueryStatusTransition(ListManager_SendFSMContext& context);
        virtual void QueryTimeoutTransition(ListManager_SendFSMContext& context);
        virtual void ReceiveTransition(ListManager_SendFSMContext& context);
        virtual void ReleaseControlTransition(ListManager_SendFSMContext& context);
        virtual void RequestControlTransition(ListManager_SendFSMContext& context);
        virtual void ResetTransition(ListManager_SendFSMContext& context);
        virtual void ResumeTransition(ListManager_SendFSMContext& context);
        virtual void SendTransition(ListManager_SendFSMContext& context);
        virtual void SetAuthorityTransition(ListManager_SendFSMContext& context);
        virtual void SetElementTransition(ListManager_SendFSMContext& context);
        virtual void SetEmergencyTransition(ListManager_SendFSMContext& context);
        virtual void ShutdownTransition(ListManager_SendFSMContext& context);
        virtual void StandbyTransition(ListManager_SendFSMContext& context);
        virtual void TimeoutTransition(ListManager_SendFSMContext& context);
        virtual void UpdateEventTransition(ListManager_SendFSMContext& context);

    protected:

        virtual void Default(ListManager_SendFSMContext& context);
    };

    class ListManager_SendFSM_SM
    {
    public:

        static ListManager_SendFSM_SM_Sending Sending;
        static ListManager_SendFSM_SM_Internally_Generated_State_DO_NOT_USE Internally_Generated_State_DO_NOT_USE;
    };

    class ListManager_SendFSM_SM_Default :
        public ListManager_SendFSMState
    {
    public:

        ListManager_SendFSM_SM_Default(const char *name, int stateId)
        : ListManager_SendFSMState(name, stateId)
        {};

    };

    class ListManager_SendFSM_SM_Sending :
        public ListManager_SendFSM_SM_Default
    {
    public:
        ListManager_SendFSM_SM_Sending(const char *name, int stateId)
        : ListManager_SendFSM_SM_Default(name, stateId)
        {};

    };

    class ListManager_SendFSM_SM_Internally_Generated_State_DO_NOT_USE :
        public ListManager_SendFSM_SM_Default
    {
    public:
        ListManager_SendFSM_SM_Internally_Generated_State_DO_NOT_USE(const char *name, int stateId)
        : ListManager_SendFSM_SM_Default(name, stateId)
        {};

        void BroadcastGlobalTransition(ListManager_SendFSMContext& context);
        void BroadcastLocalTransition(ListManager_SendFSMContext& context);
        void CancelEventTransition(ListManager_SendFSMContext& context);
        void ClearEmergencyTransition(ListManager_SendFSMContext& context);
        void CreateEventTransition(ListManager_SendFSMContext& context);
        void DeleteElementTransition(ListManager_SendFSMContext& context);
        void EventErrorTransition(ListManager_SendFSMContext& context);
        void EventOccurredTransition(ListManager_SendFSMContext& context);
        void FailureTransition(ListManager_SendFSMContext& context);
        void InitializedTransition(ListManager_SendFSMContext& context);
        void QueryAuthorityTransition(ListManager_SendFSMContext& context);
        void QueryControlTransition(ListManager_SendFSMContext& context);
        void QueryElementCountTransition(ListManager_SendFSMContext& context);
        void QueryElementListTransition(ListManager_SendFSMContext& context);
        void QueryElementTransition(ListManager_SendFSMContext& context);
        void QueryEventsTransition(ListManager_SendFSMContext& context);
        void QueryStatusTransition(ListManager_SendFSMContext& context);
        void QueryTimeoutTransition(ListManager_SendFSMContext& context);
        void ReceiveTransition(ListManager_SendFSMContext& context);
        void ReleaseControlTransition(ListManager_SendFSMContext& context);
        void RequestControlTransition(ListManager_SendFSMContext& context);
        void ResetTransition(ListManager_SendFSMContext& context);
        void ResumeTransition(ListManager_SendFSMContext& context);
        void SendTransition(ListManager_SendFSMContext& context);
        void SetAuthorityTransition(ListManager_SendFSMContext& context);
        void SetElementTransition(ListManager_SendFSMContext& context);
        void SetEmergencyTransition(ListManager_SendFSMContext& context);
        void ShutdownTransition(ListManager_SendFSMContext& context);
        void StandbyTransition(ListManager_SendFSMContext& context);
        void TimeoutTransition(ListManager_SendFSMContext& context);
        void UpdateEventTransition(ListManager_SendFSMContext& context);
    };

    class ListManager_SendFSMContext :
        public statemap::FSMContext
    {
    public:

        ListManager_SendFSMContext(ListManager_SendFSM& owner)
        : FSMContext(ListManager_SendFSM_SM::Sending),
          _owner(owner)
        {};

        ListManager_SendFSMContext(ListManager_SendFSM& owner, const statemap::State& state)
        : FSMContext(state),
          _owner(owner)
        {};

        virtual void enterStartState()
        {
            getState().Entry(*this);
            return;
        }

        ListManager_SendFSM& getOwner() const
        {
            return (_owner);
        };

        ListManager_SendFSMState& getState() const
        {
            if (_state == NULL)
            {
                throw statemap::StateUndefinedException();
            }

            return (dynamic_cast<ListManager_SendFSMState&>(*_state));
        };

        void BroadcastGlobalTransition()
        {
            setTransition("BroadcastGlobalTransition");
            (getState()).BroadcastGlobalTransition(*this);
            setTransition(NULL);
        };

        void BroadcastLocalTransition()
        {
            setTransition("BroadcastLocalTransition");
            (getState()).BroadcastLocalTransition(*this);
            setTransition(NULL);
        };

        void CancelEventTransition()
        {
            setTransition("CancelEventTransition");
            (getState()).CancelEventTransition(*this);
            setTransition(NULL);
        };

        void ClearEmergencyTransition()
        {
            setTransition("ClearEmergencyTransition");
            (getState()).ClearEmergencyTransition(*this);
            setTransition(NULL);
        };

        void CreateEventTransition()
        {
            setTransition("CreateEventTransition");
            (getState()).CreateEventTransition(*this);
            setTransition(NULL);
        };

        void DeleteElementTransition()
        {
            setTransition("DeleteElementTransition");
            (getState()).DeleteElementTransition(*this);
            setTransition(NULL);
        };

        void EventErrorTransition()
        {
            setTransition("EventErrorTransition");
            (getState()).EventErrorTransition(*this);
            setTransition(NULL);
        };

        void EventOccurredTransition()
        {
            setTransition("EventOccurredTransition");
            (getState()).EventOccurredTransition(*this);
            setTransition(NULL);
        };

        void FailureTransition()
        {
            setTransition("FailureTransition");
            (getState()).FailureTransition(*this);
            setTransition(NULL);
        };

        void InitializedTransition()
        {
            setTransition("InitializedTransition");
            (getState()).InitializedTransition(*this);
            setTransition(NULL);
        };

        void QueryAuthorityTransition()
        {
            setTransition("QueryAuthorityTransition");
            (getState()).QueryAuthorityTransition(*this);
            setTransition(NULL);
        };

        void QueryControlTransition()
        {
            setTransition("QueryControlTransition");
            (getState()).QueryControlTransition(*this);
            setTransition(NULL);
        };

        void QueryElementCountTransition()
        {
            setTransition("QueryElementCountTransition");
            (getState()).QueryElementCountTransition(*this);
            setTransition(NULL);
        };

        void QueryElementListTransition()
        {
            setTransition("QueryElementListTransition");
            (getState()).QueryElementListTransition(*this);
            setTransition(NULL);
        };

        void QueryElementTransition()
        {
            setTransition("QueryElementTransition");
            (getState()).QueryElementTransition(*this);
            setTransition(NULL);
        };

        void QueryEventsTransition()
        {
            setTransition("QueryEventsTransition");
            (getState()).QueryEventsTransition(*this);
            setTransition(NULL);
        };

        void QueryStatusTransition()
        {
            setTransition("QueryStatusTransition");
            (getState()).QueryStatusTransition(*this);
            setTransition(NULL);
        };

        void QueryTimeoutTransition()
        {
            setTransition("QueryTimeoutTransition");
            (getState()).QueryTimeoutTransition(*this);
            setTransition(NULL);
        };

        void ReceiveTransition()
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this);
            setTransition(NULL);
        };

        void ReleaseControlTransition()
        {
            setTransition("ReleaseControlTransition");
            (getState()).ReleaseControlTransition(*this);
            setTransition(NULL);
        };

        void RequestControlTransition()
        {
            setTransition("RequestControlTransition");
            (getState()).RequestControlTransition(*this);
            setTransition(NULL);
        };

        void ResetTransition()
        {
            setTransition("ResetTransition");
            (getState()).ResetTransition(*this);
            setTransition(NULL);
        };

        void ResumeTransition()
        {
            setTransition("ResumeTransition");
            (getState()).ResumeTransition(*this);
            setTransition(NULL);
        };

        void SendTransition()
        {
            setTransition("SendTransition");
            (getState()).SendTransition(*this);
            setTransition(NULL);
        };

        void SetAuthorityTransition()
        {
            setTransition("SetAuthorityTransition");
            (getState()).SetAuthorityTransition(*this);
            setTransition(NULL);
        };

        void SetElementTransition()
        {
            setTransition("SetElementTransition");
            (getState()).SetElementTransition(*this);
            setTransition(NULL);
        };

        void SetEmergencyTransition()
        {
            setTransition("SetEmergencyTransition");
            (getState()).SetEmergencyTransition(*this);
            setTransition(NULL);
        };

        void ShutdownTransition()
        {
            setTransition("ShutdownTransition");
            (getState()).ShutdownTransition(*this);
            setTransition(NULL);
        };

        void StandbyTransition()
        {
            setTransition("StandbyTransition");
            (getState()).StandbyTransition(*this);
            setTransition(NULL);
        };

        void TimeoutTransition()
        {
            setTransition("TimeoutTransition");
            (getState()).TimeoutTransition(*this);
            setTransition(NULL);
        };

        void UpdateEventTransition()
        {
            setTransition("UpdateEventTransition");
            (getState()).UpdateEventTransition(*this);
            setTransition(NULL);
        };

    private:

        ListManager_SendFSM& _owner;
    };
}


/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */

#endif // _H_LISTMANAGER_SENDFSM_SM
