#ifndef URN_JAUS_JSS_CORE_TRANSPORT_1_0_INTERNALEVENTSSET
#define URN_JAUS_JSS_CORE_TRANSPORT_1_0_INTERNALEVENTSSET

#include "BroadcastGlobal.h"
#include "BroadcastLocal.h"

#endif //URN_JAUS_JSS_CORE_TRANSPORT_1_0_INTERNALEVENTSSET
