/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : Transport_SendFSM.sm
 */

#include "urn_jaus_jss_core_Transport_1_1/Messages/MessageSet.h"
#include "urn_jaus_jss_core_Transport_1_1/Transport_SendFSM.h"
#include "include/urn_jaus_jss_core_Transport_1_1/Transport_SendFSM_sm.h"

using namespace statemap;

namespace urn_jaus_jss_core_Transport_1_1
{
    // Static class declarations.
    Transport_SendFSM_SM_Sending Transport_SendFSM_SM::Sending("Transport_SendFSM_SM::Sending", 0);
    Transport_SendFSM_SM_Internally_Generated_State_DO_NOT_USE Transport_SendFSM_SM::Internally_Generated_State_DO_NOT_USE("Transport_SendFSM_SM::Internally_Generated_State_DO_NOT_USE", 1);

    void Transport_SendFSMState::BroadcastGlobalTransition(Transport_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Transport_SendFSMState::BroadcastGlobalTransition(Transport_SendFSMContext& context, BroadcastGlobal msg)
    {
        Default(context);
        return;
    }

    void Transport_SendFSMState::BroadcastLocalTransition(Transport_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Transport_SendFSMState::BroadcastLocalTransition(Transport_SendFSMContext& context, BroadcastLocal msg)
    {
        Default(context);
        return;
    }

    void Transport_SendFSMState::ReceiveTransition(Transport_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Transport_SendFSMState::SendTransition(Transport_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void Transport_SendFSMState::SendTransition(Transport_SendFSMContext& context, Send msg)
    {
        Default(context);
        return;
    }

    void Transport_SendFSMState::Default(Transport_SendFSMContext& context)
    {
        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Default"
                << std::endl;
        }

        throw (
            TransitionUndefinedException(
                context.getState().getName(),
                context.getTransition()));

        return;
    }

    void Transport_SendFSM_SM_Sending::BroadcastGlobalTransition(Transport_SendFSMContext& context, BroadcastGlobal msg)
    {
        Transport_SendFSM& ctxt(context.getOwner());

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Transport_SendFSM_SM BroadcastGlobalTransition(BroadcastGlobal msg)"
                << std::endl;
        }

        Transport_SendFSMState& endState = context.getState();

        context.clearState();
        try
        {
            ctxt.BroadcastGlobalEnqueueAction(msg);
            context.setState(endState);
        }
        catch (...)
        {
            context.setState(endState);
            throw;
        }

        return;
    }

    void Transport_SendFSM_SM_Sending::BroadcastLocalTransition(Transport_SendFSMContext& context, BroadcastLocal msg)
    {
        Transport_SendFSM& ctxt(context.getOwner());

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Transport_SendFSM_SM BroadcastLocalTransition(BroadcastLocal msg)"
                << std::endl;
        }

        Transport_SendFSMState& endState = context.getState();

        context.clearState();
        try
        {
            ctxt.BroadcastLocalEnqueueAction(msg);
            context.setState(endState);
        }
        catch (...)
        {
            context.setState(endState);
            throw;
        }

        return;
    }

    void Transport_SendFSM_SM_Sending::SendTransition(Transport_SendFSMContext& context, Send msg)
    {
        Transport_SendFSM& ctxt(context.getOwner());

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Transport_SendFSM_SM SendTransition(Send msg)"
                << std::endl;
        }

        Transport_SendFSMState& endState = context.getState();

        context.clearState();
        try
        {
            ctxt.EnqueueAction(msg);
            context.setState(endState);
        }
        catch (...)
        {
            context.setState(endState);
            throw;
        }

        return;
    }

    void Transport_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::BroadcastGlobalTransition(Transport_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Transport_SendFSM_SM BroadcastGlobalTransition()"
                << std::endl;
        }


        return;
    }

    void Transport_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::BroadcastLocalTransition(Transport_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Transport_SendFSM_SM BroadcastLocalTransition()"
                << std::endl;
        }


        return;
    }

    void Transport_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::ReceiveTransition(Transport_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Transport_SendFSM_SM ReceiveTransition()"
                << std::endl;
        }


        return;
    }

    void Transport_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::SendTransition(Transport_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Transport_SendFSM_SM SendTransition()"
                << std::endl;
        }


        return;
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
