/*
 * generated by Xtext
 */
package org.jts.eclipse;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CjsidlRuntimeModule extends org.jts.eclipse.AbstractCjsidlRuntimeModule {

}
