/*
* generated by Xtext
*/
package org.jts.eclipse.ui.contentassist;

import org.jts.eclipse.ui.contentassist.AbstractCjsidlProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CjsidlProposalProvider extends AbstractCjsidlProposalProvider {

}
