/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : UnsolicitedHeartbeat_SendFSM_sm.sm
 */

#include "urn_jaus_jss_iop_UnsolicitedHeartbeat_1_1/Messages/MessageSet.h"
#include "urn_jaus_jss_iop_UnsolicitedHeartbeat_1_1/UnsolicitedHeartbeat_SendFSM.h"
#include "include/urn_jaus_jss_iop_UnsolicitedHeartbeat_1_1/UnsolicitedHeartbeat_SendFSM_sm.h"

using namespace statemap;

namespace urn_jaus_jss_iop_UnsolicitedHeartbeat_1_1
{
    // Static class declarations.
    UnsolicitedHeartbeat_SendFSM_SM_Sending UnsolicitedHeartbeat_SendFSM_SM::Sending("UnsolicitedHeartbeat_SendFSM_SM::Sending", 0);
    UnsolicitedHeartbeat_SendFSM_SM_Internally_Generated_State_DO_NOT_USE UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE("UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE", 1);

    void UnsolicitedHeartbeat_SendFSMState::BroadcastGlobalTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void UnsolicitedHeartbeat_SendFSMState::BroadcastLocalTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void UnsolicitedHeartbeat_SendFSMState::CancelEventTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void UnsolicitedHeartbeat_SendFSMState::CommandCompletedTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void UnsolicitedHeartbeat_SendFSMState::CommandExpiredTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void UnsolicitedHeartbeat_SendFSMState::CreateCommandEventTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void UnsolicitedHeartbeat_SendFSMState::CreateEventTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void UnsolicitedHeartbeat_SendFSMState::EventErrorTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void UnsolicitedHeartbeat_SendFSMState::EventOccurredTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void UnsolicitedHeartbeat_SendFSMState::PeriodicTimerTriggerTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void UnsolicitedHeartbeat_SendFSMState::QueryEventTimeoutTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void UnsolicitedHeartbeat_SendFSMState::QueryEventsTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void UnsolicitedHeartbeat_SendFSMState::QueryHeartbeatPulseTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void UnsolicitedHeartbeat_SendFSMState::ReceiveTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void UnsolicitedHeartbeat_SendFSMState::SendTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void UnsolicitedHeartbeat_SendFSMState::TimeoutTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void UnsolicitedHeartbeat_SendFSMState::UpdateEventTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void UnsolicitedHeartbeat_SendFSMState::Default(UnsolicitedHeartbeat_SendFSMContext& context)
    {
        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Default"
                << std::endl;
        }

        throw (
            TransitionUndefinedException(
                context.getState().getName(),
                context.getTransition()));

        return;
    }

    void UnsolicitedHeartbeat_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::BroadcastGlobalTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastGlobalTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastGlobalTransition()"
                << std::endl;
        }


        return;
    }

    void UnsolicitedHeartbeat_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::BroadcastLocalTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastLocalTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastLocalTransition()"
                << std::endl;
        }


        return;
    }

    void UnsolicitedHeartbeat_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::CancelEventTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::CancelEventTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::CancelEventTransition()"
                << std::endl;
        }


        return;
    }

    void UnsolicitedHeartbeat_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::CommandCompletedTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::CommandCompletedTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::CommandCompletedTransition()"
                << std::endl;
        }


        return;
    }

    void UnsolicitedHeartbeat_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::CommandExpiredTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::CommandExpiredTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::CommandExpiredTransition()"
                << std::endl;
        }


        return;
    }

    void UnsolicitedHeartbeat_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::CreateCommandEventTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::CreateCommandEventTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::CreateCommandEventTransition()"
                << std::endl;
        }


        return;
    }

    void UnsolicitedHeartbeat_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::CreateEventTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::CreateEventTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::CreateEventTransition()"
                << std::endl;
        }


        return;
    }

    void UnsolicitedHeartbeat_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::EventErrorTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::EventErrorTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::EventErrorTransition()"
                << std::endl;
        }


        return;
    }

    void UnsolicitedHeartbeat_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::EventOccurredTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::EventOccurredTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::EventOccurredTransition()"
                << std::endl;
        }


        return;
    }

    void UnsolicitedHeartbeat_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::PeriodicTimerTriggerTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::PeriodicTimerTriggerTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::PeriodicTimerTriggerTransition()"
                << std::endl;
        }


        return;
    }

    void UnsolicitedHeartbeat_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryEventTimeoutTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryEventTimeoutTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryEventTimeoutTransition()"
                << std::endl;
        }


        return;
    }

    void UnsolicitedHeartbeat_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryEventsTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryEventsTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryEventsTransition()"
                << std::endl;
        }


        return;
    }

    void UnsolicitedHeartbeat_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryHeartbeatPulseTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryHeartbeatPulseTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryHeartbeatPulseTransition()"
                << std::endl;
        }


        return;
    }

    void UnsolicitedHeartbeat_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::ReceiveTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ReceiveTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ReceiveTransition()"
                << std::endl;
        }


        return;
    }

    void UnsolicitedHeartbeat_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::SendTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::SendTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::SendTransition()"
                << std::endl;
        }


        return;
    }

    void UnsolicitedHeartbeat_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::TimeoutTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::TimeoutTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::TimeoutTransition()"
                << std::endl;
        }


        return;
    }

    void UnsolicitedHeartbeat_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::UpdateEventTransition(UnsolicitedHeartbeat_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::UpdateEventTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : UnsolicitedHeartbeat_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::UpdateEventTransition()"
                << std::endl;
        }


        return;
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
