/* Generated By:JavaCC: Do not edit this line. GuardParserConstants.java */
package org.jts.validator.parsers;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GuardParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TRUE = 3;
  /** RegularExpression Id. */
  int FALSE = 4;
  /** RegularExpression Id. */
  int ID = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"true\"",
    "\"false\"",
    "<ID>",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\"!=\"",
    "\"!\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"\\\'\"",
  };

}
