#ifndef URN_JAUS_EXAMPLE_ADDITION_CLIENT_1_0_INTERNALEVENTSSET
#define URN_JAUS_EXAMPLE_ADDITION_CLIENT_1_0_INTERNALEVENTSSET

#include "InitToReadyEventDef.h"

#endif //URN_JAUS_EXAMPLE_ADDITION_CLIENT_1_0_INTERNALEVENTSSET
