/***********           LICENSE HEADER   *******************************
JAUS Tool Set
Copyright (c)  2010, United States Government
All rights reserved.

Redistribution and use in source and binary forms, with or without 
modification, are permitted provided that the following conditions are met:

       Redistributions of source code must retain the above copyright notice, 
this list of conditions and the following disclaimer.

       Redistributions in binary form must reproduce the above copyright 
notice, this list of conditions and the following disclaimer in the 
documentation and/or other materials provided with the distribution.

       Neither the name of the United States Government nor the names of 
its contributors may be used to endorse or promote products derived from 
this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
POSSIBILITY OF SUCH DAMAGE.
*********************  END OF LICENSE ***********************************/

#ifndef _H_COMMSTESTSERVERFSM_SM
#define _H_COMMSTESTSERVERFSM_SM

/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : CommsTestServerFSM.sm
 */


#define SMC_USES_IOSTREAMS

#include <statemap.h>

namespace urn_jts_comms_test_server_1_0
{
    // Forward declarations.
    class CommsTestServerFSM_SM;
    class CommsTestServerFSM_SM_Running;
    class CommsTestServerFSM_SM_Default;
    class CommsTestServerFSMState;
    class CommsTestServerFSMContext;
    class CommsTestServerFSM;

    class CommsTestServerFSMState :
        public statemap::State
    {
    public:

        CommsTestServerFSMState(const char *name, int stateId)
        : statemap::State(name, stateId)
        {};

        virtual void Entry(CommsTestServerFSMContext&) {};
        virtual void Exit(CommsTestServerFSMContext&) {};

        virtual void CommsTestMsgTransition(CommsTestServerFSMContext& context, CommsTestMsg msg, JausAddress sender);
        virtual void QueryServicesTransition(CommsTestServerFSMContext& context, QueryServices msg, JausAddress sender);

    protected:

        virtual void Default(CommsTestServerFSMContext& context);
    };

    class CommsTestServerFSM_SM
    {
    public:

        static CommsTestServerFSM_SM_Running Running;
    };

    class CommsTestServerFSM_SM_Default :
        public CommsTestServerFSMState
    {
    public:

        CommsTestServerFSM_SM_Default(const char *name, int stateId)
        : CommsTestServerFSMState(name, stateId)
        {};

    };

    class CommsTestServerFSM_SM_Running :
        public CommsTestServerFSM_SM_Default
    {
    public:
        CommsTestServerFSM_SM_Running(const char *name, int stateId)
        : CommsTestServerFSM_SM_Default(name, stateId)
        {};

        void CommsTestMsgTransition(CommsTestServerFSMContext& context, CommsTestMsg msg, JausAddress sender);
        void QueryServicesTransition(CommsTestServerFSMContext& context, QueryServices msg, JausAddress sender);
    };

    class CommsTestServerFSMContext :
        public statemap::FSMContext
    {
    public:

        CommsTestServerFSMContext(CommsTestServerFSM& owner)
        : FSMContext(CommsTestServerFSM_SM::Running),
          _owner(owner)
        {};

        CommsTestServerFSMContext(CommsTestServerFSM& owner, const statemap::State& state)
        : FSMContext(state),
          _owner(owner)
        {};

        virtual void enterStartState()
        {
            getState().Entry(*this);
            return;
        }

        CommsTestServerFSM& getOwner() const
        {
            return (_owner);
        };

        CommsTestServerFSMState& getState() const
        {
            if (_state == NULL)
            {
                throw statemap::StateUndefinedException();
            }

            return (dynamic_cast<CommsTestServerFSMState&>(*_state));
        };

        void CommsTestMsgTransition(CommsTestMsg msg, JausAddress sender)
        {
            setTransition("CommsTestMsgTransition");
            (getState()).CommsTestMsgTransition(*this, msg, sender);
            setTransition(NULL);
        };

        void QueryServicesTransition(QueryServices msg, JausAddress sender)
        {
            setTransition("QueryServicesTransition");
            (getState()).QueryServicesTransition(*this, msg, sender);
            setTransition(NULL);
        };

    private:

        CommsTestServerFSM& _owner;
    };
}


/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */

#endif // _H_COMMSTESTSERVERFSM_SM
