#ifndef URN_JTS_EXAMPLE_MANAGEMENT_OCU_1_0_INTERNALEVENTSSET
#define URN_JTS_EXAMPLE_MANAGEMENT_OCU_1_0_INTERNALEVENTSSET

#include "MenuItemEntered.h"

#endif //URN_JTS_EXAMPLE_MANAGEMENT_OCU_1_0_INTERNALEVENTSSET
