#ifndef _H_DISCOVERY_SENDFSM_SM
#define _H_DISCOVERY_SENDFSM_SM

/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : Discovery_SendFSM_sm.sm
 */


#define SMC_USES_IOSTREAMS

#include <statemap.h>

namespace urn_jaus_jss_core_Discovery_1_1
{
    // Forward declarations.
    class Discovery_SendFSM_SM;
    class Discovery_SendFSM_SM_Sending;
    class Discovery_SendFSM_SM_Internally_Generated_State_DO_NOT_USE;
    class Discovery_SendFSM_SM_Default;
    class Discovery_SendFSMState;
    class Discovery_SendFSMContext;
    class Discovery_SendFSM;

    class Discovery_SendFSMState :
        public statemap::State
    {
    public:

        Discovery_SendFSMState(const char *name, int stateId)
        : statemap::State(name, stateId)
        {};

        virtual void Entry(Discovery_SendFSMContext&) {};
        virtual void Exit(Discovery_SendFSMContext&) {};

        virtual void BroadcastGlobalTransition(Discovery_SendFSMContext& context);
        virtual void BroadcastLocalTransition(Discovery_SendFSMContext& context);
        virtual void CancelEventTransition(Discovery_SendFSMContext& context);
        virtual void CommandCompletedTransition(Discovery_SendFSMContext& context);
        virtual void CommandExpiredTransition(Discovery_SendFSMContext& context);
        virtual void CreateCommandEventTransition(Discovery_SendFSMContext& context);
        virtual void CreateEventTransition(Discovery_SendFSMContext& context);
        virtual void EventErrorTransition(Discovery_SendFSMContext& context);
        virtual void EventOccurredTransition(Discovery_SendFSMContext& context);
        virtual void QueryConfigurationTransition(Discovery_SendFSMContext& context);
        virtual void QueryEventTimeoutTransition(Discovery_SendFSMContext& context);
        virtual void QueryEventsTransition(Discovery_SendFSMContext& context);
        virtual void QueryIdentificationTransition(Discovery_SendFSMContext& context);
        virtual void QueryServiceListTransition(Discovery_SendFSMContext& context);
        virtual void QueryServicesTransition(Discovery_SendFSMContext& context);
        virtual void QuerySubsystemListTransition(Discovery_SendFSMContext& context);
        virtual void ReceiveTransition(Discovery_SendFSMContext& context);
        virtual void RegisterServicesTransition(Discovery_SendFSMContext& context);
        virtual void SendTransition(Discovery_SendFSMContext& context);
        virtual void TimeoutTransition(Discovery_SendFSMContext& context);
        virtual void UpdateEventTransition(Discovery_SendFSMContext& context);

    protected:

        virtual void Default(Discovery_SendFSMContext& context);
    };

    class Discovery_SendFSM_SM
    {
    public:

        static Discovery_SendFSM_SM_Sending Sending;
        static Discovery_SendFSM_SM_Internally_Generated_State_DO_NOT_USE Internally_Generated_State_DO_NOT_USE;
    };

    class Discovery_SendFSM_SM_Default :
        public Discovery_SendFSMState
    {
    public:

        Discovery_SendFSM_SM_Default(const char *name, int stateId)
        : Discovery_SendFSMState(name, stateId)
        {};

    };

    class Discovery_SendFSM_SM_Sending :
        public Discovery_SendFSM_SM_Default
    {
    public:
        Discovery_SendFSM_SM_Sending(const char *name, int stateId)
        : Discovery_SendFSM_SM_Default(name, stateId)
        {};

    };

    class Discovery_SendFSM_SM_Internally_Generated_State_DO_NOT_USE :
        public Discovery_SendFSM_SM_Default
    {
    public:
        Discovery_SendFSM_SM_Internally_Generated_State_DO_NOT_USE(const char *name, int stateId)
        : Discovery_SendFSM_SM_Default(name, stateId)
        {};

        void BroadcastGlobalTransition(Discovery_SendFSMContext& context);
        void BroadcastLocalTransition(Discovery_SendFSMContext& context);
        void CancelEventTransition(Discovery_SendFSMContext& context);
        void CommandCompletedTransition(Discovery_SendFSMContext& context);
        void CommandExpiredTransition(Discovery_SendFSMContext& context);
        void CreateCommandEventTransition(Discovery_SendFSMContext& context);
        void CreateEventTransition(Discovery_SendFSMContext& context);
        void EventErrorTransition(Discovery_SendFSMContext& context);
        void EventOccurredTransition(Discovery_SendFSMContext& context);
        void QueryConfigurationTransition(Discovery_SendFSMContext& context);
        void QueryEventTimeoutTransition(Discovery_SendFSMContext& context);
        void QueryEventsTransition(Discovery_SendFSMContext& context);
        void QueryIdentificationTransition(Discovery_SendFSMContext& context);
        void QueryServiceListTransition(Discovery_SendFSMContext& context);
        void QueryServicesTransition(Discovery_SendFSMContext& context);
        void QuerySubsystemListTransition(Discovery_SendFSMContext& context);
        void ReceiveTransition(Discovery_SendFSMContext& context);
        void RegisterServicesTransition(Discovery_SendFSMContext& context);
        void SendTransition(Discovery_SendFSMContext& context);
        void TimeoutTransition(Discovery_SendFSMContext& context);
        void UpdateEventTransition(Discovery_SendFSMContext& context);
    };

    class Discovery_SendFSMContext :
        public statemap::FSMContext
    {
    public:

        Discovery_SendFSMContext(Discovery_SendFSM& owner)
        : FSMContext(Discovery_SendFSM_SM::Sending),
          _owner(owner)
        {};

        Discovery_SendFSMContext(Discovery_SendFSM& owner, const statemap::State& state)
        : FSMContext(state),
          _owner(owner)
        {};

        virtual void enterStartState()
        {
            getState().Entry(*this);
            return;
        }

        Discovery_SendFSM& getOwner() const
        {
            return (_owner);
        };

        Discovery_SendFSMState& getState() const
        {
            if (_state == NULL)
            {
                throw statemap::StateUndefinedException();
            }

            return (dynamic_cast<Discovery_SendFSMState&>(*_state));
        };

        void BroadcastGlobalTransition()
        {
            setTransition("BroadcastGlobalTransition");
            (getState()).BroadcastGlobalTransition(*this);
            setTransition(NULL);
        };

        void BroadcastLocalTransition()
        {
            setTransition("BroadcastLocalTransition");
            (getState()).BroadcastLocalTransition(*this);
            setTransition(NULL);
        };

        void CancelEventTransition()
        {
            setTransition("CancelEventTransition");
            (getState()).CancelEventTransition(*this);
            setTransition(NULL);
        };

        void CommandCompletedTransition()
        {
            setTransition("CommandCompletedTransition");
            (getState()).CommandCompletedTransition(*this);
            setTransition(NULL);
        };

        void CommandExpiredTransition()
        {
            setTransition("CommandExpiredTransition");
            (getState()).CommandExpiredTransition(*this);
            setTransition(NULL);
        };

        void CreateCommandEventTransition()
        {
            setTransition("CreateCommandEventTransition");
            (getState()).CreateCommandEventTransition(*this);
            setTransition(NULL);
        };

        void CreateEventTransition()
        {
            setTransition("CreateEventTransition");
            (getState()).CreateEventTransition(*this);
            setTransition(NULL);
        };

        void EventErrorTransition()
        {
            setTransition("EventErrorTransition");
            (getState()).EventErrorTransition(*this);
            setTransition(NULL);
        };

        void EventOccurredTransition()
        {
            setTransition("EventOccurredTransition");
            (getState()).EventOccurredTransition(*this);
            setTransition(NULL);
        };

        void QueryConfigurationTransition()
        {
            setTransition("QueryConfigurationTransition");
            (getState()).QueryConfigurationTransition(*this);
            setTransition(NULL);
        };

        void QueryEventTimeoutTransition()
        {
            setTransition("QueryEventTimeoutTransition");
            (getState()).QueryEventTimeoutTransition(*this);
            setTransition(NULL);
        };

        void QueryEventsTransition()
        {
            setTransition("QueryEventsTransition");
            (getState()).QueryEventsTransition(*this);
            setTransition(NULL);
        };

        void QueryIdentificationTransition()
        {
            setTransition("QueryIdentificationTransition");
            (getState()).QueryIdentificationTransition(*this);
            setTransition(NULL);
        };

        void QueryServiceListTransition()
        {
            setTransition("QueryServiceListTransition");
            (getState()).QueryServiceListTransition(*this);
            setTransition(NULL);
        };

        void QueryServicesTransition()
        {
            setTransition("QueryServicesTransition");
            (getState()).QueryServicesTransition(*this);
            setTransition(NULL);
        };

        void QuerySubsystemListTransition()
        {
            setTransition("QuerySubsystemListTransition");
            (getState()).QuerySubsystemListTransition(*this);
            setTransition(NULL);
        };

        void ReceiveTransition()
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this);
            setTransition(NULL);
        };

        void RegisterServicesTransition()
        {
            setTransition("RegisterServicesTransition");
            (getState()).RegisterServicesTransition(*this);
            setTransition(NULL);
        };

        void SendTransition()
        {
            setTransition("SendTransition");
            (getState()).SendTransition(*this);
            setTransition(NULL);
        };

        void TimeoutTransition()
        {
            setTransition("TimeoutTransition");
            (getState()).TimeoutTransition(*this);
            setTransition(NULL);
        };

        void UpdateEventTransition()
        {
            setTransition("UpdateEventTransition");
            (getState()).UpdateEventTransition(*this);
            setTransition(NULL);
        };

    private:

        Discovery_SendFSM& _owner;
    };
}


/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */

#endif // _H_DISCOVERY_SENDFSM_SM
