/***********           LICENSE HEADER   *******************************
JAUS Tool Set
Copyright (c)  2010, United States Government
All rights reserved.

Redistribution and use in source and binary forms, with or without 
modification, are permitted provided that the following conditions are met:

       Redistributions of source code must retain the above copyright notice, 
this list of conditions and the following disclaimer.

       Redistributions in binary form must reproduce the above copyright 
notice, this list of conditions and the following disclaimer in the 
documentation and/or other materials provided with the distribution.

       Neither the name of the United States Government nor the names of 
its contributors may be used to endorse or promote products derived from 
this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
POSSIBILITY OF SUCH DAMAGE.
*********************  END OF LICENSE ***********************************/

/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : CommsTestClientFSM.sm
 */

#include <MessageSet.h>
#include "CommsTestClientFSM.h"
#include "include/CommsTestClientFSM_sm.h"

using namespace statemap;

namespace urn_jts_comms_test_client_1_0
{
    // Static class declarations.
    CommsTestClientFSM_SM_Running CommsTestClientFSM_SM::Running("CommsTestClientFSM_SM::Running", 0);
    CommsTestClientFSM_SM_Waiting CommsTestClientFSM_SM::Waiting("CommsTestClientFSM_SM::Waiting", 1);

    void CommsTestClientFSMState::CommsTestMsgTransition(CommsTestClientFSMContext& context, CommsTestMsg msg, JausAddress sender)
    {
        Default(context);
        return;
    }

    void CommsTestClientFSMState::reportServicesTransition(CommsTestClientFSMContext& context, ReportServices msg, JausAddress sender)
    {
        Default(context);
        return;
    }

    void CommsTestClientFSMState::timeoutTransition(CommsTestClientFSMContext& context)
    {
        Default(context);
        return;
    }

    void CommsTestClientFSMState::Default(CommsTestClientFSMContext& context)
    {
        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Default"
                << std::endl;
        }

        throw (
            TransitionUndefinedException(
                context.getState().getName(),
                context.getTransition()));

        return;
    }

    void CommsTestClientFSM_SM_Running::CommsTestMsgTransition(CommsTestClientFSMContext& context, CommsTestMsg msg, JausAddress sender)
    {
        CommsTestClientFSM& ctxt(context.getOwner());

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : CommsTestClientFSM_SM CommsTestMsgTransition(CommsTestMsg msg, JausAddress sender)"
                << std::endl;
        }

        (context.getState()).Exit(context);
        context.clearState();
        try
        {
            ctxt.processSuccessAction(msg);
            ctxt.sendCommsTestMsgAction();
            context.setState(CommsTestClientFSM_SM::Running);
        }
        catch (...)
        {
            context.setState(CommsTestClientFSM_SM::Running);
            throw;
        }
        (context.getState()).Entry(context);

        return;
    }

    void CommsTestClientFSM_SM_Running::timeoutTransition(CommsTestClientFSMContext& context)
    {
        CommsTestClientFSM& ctxt(context.getOwner());

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : CommsTestClientFSM_SM timeoutTransition()"
                << std::endl;
        }

        (context.getState()).Exit(context);
        context.clearState();
        try
        {
            ctxt.processFailureAction();
            ctxt.sendCommsTestMsgAction();
            context.setState(CommsTestClientFSM_SM::Running);
        }
        catch (...)
        {
            context.setState(CommsTestClientFSM_SM::Running);
            throw;
        }
        (context.getState()).Entry(context);

        return;
    }

    void CommsTestClientFSM_SM_Waiting::reportServicesTransition(CommsTestClientFSMContext& context, ReportServices msg, JausAddress sender)
    {
        CommsTestClientFSM& ctxt(context.getOwner());

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : CommsTestClientFSM_SM reportServicesTransition(ReportServices msg, JausAddress sender)"
                << std::endl;
        }

        if (! ctxt.isCommsTestServer(msg, sender))
        {
            (context.getState()).Exit(context);
            context.clearState();
            try
            {
                ctxt.broadcastQueryServicesAction();
                context.setState(CommsTestClientFSM_SM::Waiting);
            }
            catch (...)
            {
                context.setState(CommsTestClientFSM_SM::Waiting);
                throw;
            }
            (context.getState()).Entry(context);
        }
        else if (ctxt.isCommsTestServer(msg, sender))
    
    {
            (context.getState()).Exit(context);
            context.clearState();
            try
            {
                ctxt.setServerAddressAction(sender);
                ctxt.sendCommsTestMsgAction();
                context.setState(CommsTestClientFSM_SM::Running);
            }
            catch (...)
            {
                context.setState(CommsTestClientFSM_SM::Running);
                throw;
            }
            (context.getState()).Entry(context);
        }        else
        {
             CommsTestClientFSM_SM_Default::reportServicesTransition(context, msg, sender);
        }

        return;
    }

    void CommsTestClientFSM_SM_Waiting::timeoutTransition(CommsTestClientFSMContext& context)
    {
        CommsTestClientFSM& ctxt(context.getOwner());

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : CommsTestClientFSM_SM timeoutTransition()"
                << std::endl;
        }

        (context.getState()).Exit(context);
        context.clearState();
        try
        {
            ctxt.broadcastQueryServicesAction();
            context.setState(CommsTestClientFSM_SM::Waiting);
        }
        catch (...)
        {
            context.setState(CommsTestClientFSM_SM::Waiting);
            throw;
        }
        (context.getState()).Entry(context);

        return;
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
