#ifndef _H_MANAGEMENT_RECEIVEFSM_SM
#define _H_MANAGEMENT_RECEIVEFSM_SM

/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : Management_ReceiveFSM_sm.sm
 */


#define SMC_USES_IOSTREAMS

#include <statemap.h>

namespace urn_jaus_jss_core_Management_1_0
{
    // Forward declarations.
    class Management_ReceiveFSM_SM;
    class Management_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Standby;
    class Management_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Init;
    class Management_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Failure;
    class Management_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Shutdown;
    class Management_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Emergency;
    class Management_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Standby;
    class Management_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Ready;
    class Management_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Emergency;
    class Management_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE;
    class Management_ReceiveFSM_SM_Default;
    class Management_ReceiveFSMState;
    class Management_ReceiveFSMContext;
    class Management_ReceiveFSM;

    class Management_ReceiveFSMState :
        public statemap::State
    {
    public:

        Management_ReceiveFSMState(const char *name, int stateId)
        : statemap::State(name, stateId)
        {};

        virtual void Entry(Management_ReceiveFSMContext&) {};
        virtual void Exit(Management_ReceiveFSMContext&) {};

        virtual void BroadcastGlobalTransition(Management_ReceiveFSMContext& context);
        virtual void BroadcastLocalTransition(Management_ReceiveFSMContext& context);
        virtual void CancelEventTransition(Management_ReceiveFSMContext& context);
        virtual void ClearEmergencyTransition(Management_ReceiveFSMContext& context);
        virtual void CreateEventTransition(Management_ReceiveFSMContext& context);
        virtual void EventErrorTransition(Management_ReceiveFSMContext& context);
        virtual void EventOccurredTransition(Management_ReceiveFSMContext& context);
        virtual void FailureTransition(Management_ReceiveFSMContext& context);
        virtual void InitializedTransition(Management_ReceiveFSMContext& context);
        virtual void InternalStateChange_To_Management_ReceiveFSM_ReceivingTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_Management_ReceiveFSM_Receiving_ReadyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_ControlledTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateBTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_EmergencyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_ReadyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_StandbyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlledTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateATransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_EmergencyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_FailureTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_InitTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_ShutdownTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_StandbyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void QueryAuthorityTransition(Management_ReceiveFSMContext& context);
        virtual void QueryControlTransition(Management_ReceiveFSMContext& context);
        virtual void QueryEventsTransition(Management_ReceiveFSMContext& context);
        virtual void QueryStatusTransition(Management_ReceiveFSMContext& context);
        virtual void QueryTimeoutTransition(Management_ReceiveFSMContext& context);
        virtual void ReceiveTransition(Management_ReceiveFSMContext& context);
        virtual void ReceiveTransition(Management_ReceiveFSMContext& context, Reset msg);
        virtual void ReceiveTransition(Management_ReceiveFSMContext& context, SetAuthority msg);
        virtual void ReceiveTransition(Management_ReceiveFSMContext& context, Shutdown msg);
        virtual void ReceiveTransition(Management_ReceiveFSMContext& context, ClearEmergency msg, Receive::Body::ReceiveRec transportData);
        virtual void ReceiveTransition(Management_ReceiveFSMContext& context, QueryStatus msg, Receive::Body::ReceiveRec transportData);
        virtual void ReceiveTransition(Management_ReceiveFSMContext& context, ReleaseControl msg, Receive::Body::ReceiveRec transportData);
        virtual void ReceiveTransition(Management_ReceiveFSMContext& context, RequestControl msg, Receive::Body::ReceiveRec transportData);
        virtual void ReceiveTransition(Management_ReceiveFSMContext& context, Reset msg, Receive::Body::ReceiveRec transportData);
        virtual void ReceiveTransition(Management_ReceiveFSMContext& context, Resume msg, Receive::Body::ReceiveRec transportData);
        virtual void ReceiveTransition(Management_ReceiveFSMContext& context, SetEmergency msg, Receive::Body::ReceiveRec transportData);
        virtual void ReceiveTransition(Management_ReceiveFSMContext& context, Shutdown msg, Receive::Body::ReceiveRec transportData);
        virtual void ReceiveTransition(Management_ReceiveFSMContext& context, Standby msg, Receive::Body::ReceiveRec transportData);
        virtual void ReleaseControlTransition(Management_ReceiveFSMContext& context);
        virtual void RequestControlTransition(Management_ReceiveFSMContext& context);
        virtual void ResetTransition(Management_ReceiveFSMContext& context);
        virtual void ResumeTransition(Management_ReceiveFSMContext& context);
        virtual void SendTransition(Management_ReceiveFSMContext& context);
        virtual void SetAuthorityTransition(Management_ReceiveFSMContext& context);
        virtual void SetEmergencyTransition(Management_ReceiveFSMContext& context);
        virtual void ShutdownTransition(Management_ReceiveFSMContext& context);
        virtual void StandbyTransition(Management_ReceiveFSMContext& context);
        virtual void TimeoutTransition(Management_ReceiveFSMContext& context);
        virtual void UpdateEventTransition(Management_ReceiveFSMContext& context);

    protected:

        virtual void Default(Management_ReceiveFSMContext& context);
    };

    class Management_ReceiveFSM_SM
    {
    public:

        static Management_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Standby Receiving_Ready_NotControlled_StateA_Standby;
        static Management_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Init Receiving_Ready_NotControlled_StateA_Init;
        static Management_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Failure Receiving_Ready_NotControlled_StateA_Failure;
        static Management_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Shutdown Receiving_Ready_NotControlled_StateA_Shutdown;
        static Management_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Emergency Receiving_Ready_NotControlled_StateA_Emergency;
        static Management_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Standby Receiving_Ready_Controlled_StateB_Standby;
        static Management_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Ready Receiving_Ready_Controlled_StateB_Ready;
        static Management_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Emergency Receiving_Ready_Controlled_StateB_Emergency;
        static Management_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE Internally_Generated_State_DO_NOT_USE;
    };

    class Management_ReceiveFSM_SM_Default :
        public Management_ReceiveFSMState
    {
    public:

        Management_ReceiveFSM_SM_Default(const char *name, int stateId)
        : Management_ReceiveFSMState(name, stateId)
        {};

    };

    class Management_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Standby :
        public Management_ReceiveFSM_SM_Default
    {
    public:
        Management_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Standby(const char *name, int stateId)
        : Management_ReceiveFSM_SM_Default(name, stateId)
        {};

        void FailureTransition(Management_ReceiveFSMContext& context);
        void InternalStateChange_To_Management_ReceiveFSM_ReceivingTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_ReadyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_ControlledTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateBTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_EmergencyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_ReadyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_StandbyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlledTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateATransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_EmergencyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_FailureTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_InitTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_ShutdownTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void ReceiveTransition(Management_ReceiveFSMContext& context, QueryStatus msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(Management_ReceiveFSMContext& context, SetEmergency msg, Receive::Body::ReceiveRec transportData);
    };

    class Management_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Init :
        public Management_ReceiveFSM_SM_Default
    {
    public:
        Management_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Init(const char *name, int stateId)
        : Management_ReceiveFSM_SM_Default(name, stateId)
        {};

        void FailureTransition(Management_ReceiveFSMContext& context);
        void InitializedTransition(Management_ReceiveFSMContext& context);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_ControlledTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateBTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_EmergencyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_ReadyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_StandbyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_EmergencyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_FailureTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_ShutdownTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_StandbyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void ReceiveTransition(Management_ReceiveFSMContext& context, QueryStatus msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(Management_ReceiveFSMContext& context, SetEmergency msg, Receive::Body::ReceiveRec transportData);
    };

    class Management_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Failure :
        public Management_ReceiveFSM_SM_Default
    {
    public:
        Management_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Failure(const char *name, int stateId)
        : Management_ReceiveFSM_SM_Default(name, stateId)
        {};

        void FailureTransition(Management_ReceiveFSMContext& context);
        void InternalStateChange_To_Management_ReceiveFSM_ReceivingTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_ReadyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_ControlledTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateBTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_EmergencyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_ReadyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_StandbyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlledTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateATransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_EmergencyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_InitTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_ShutdownTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_StandbyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void ReceiveTransition(Management_ReceiveFSMContext& context, QueryStatus msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(Management_ReceiveFSMContext& context, SetEmergency msg, Receive::Body::ReceiveRec transportData);
    };

    class Management_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Shutdown :
        public Management_ReceiveFSM_SM_Default
    {
    public:
        Management_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Shutdown(const char *name, int stateId)
        : Management_ReceiveFSM_SM_Default(name, stateId)
        {};

        void FailureTransition(Management_ReceiveFSMContext& context);
        void InternalStateChange_To_Management_ReceiveFSM_ReceivingTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_ReadyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_ControlledTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateBTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_EmergencyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_ReadyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_StandbyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlledTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateATransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_EmergencyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_FailureTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_InitTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_StandbyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void ReceiveTransition(Management_ReceiveFSMContext& context, QueryStatus msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(Management_ReceiveFSMContext& context, SetEmergency msg, Receive::Body::ReceiveRec transportData);
    };

    class Management_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Emergency :
        public Management_ReceiveFSM_SM_Default
    {
    public:
        Management_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Emergency(const char *name, int stateId)
        : Management_ReceiveFSM_SM_Default(name, stateId)
        {};

        void FailureTransition(Management_ReceiveFSMContext& context);
        void InternalStateChange_To_Management_ReceiveFSM_ReceivingTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_ReadyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_ControlledTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateBTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_EmergencyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_ReadyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_StandbyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlledTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateATransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_FailureTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_InitTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_ShutdownTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_StandbyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void ReceiveTransition(Management_ReceiveFSMContext& context, Reset msg);
        void ReceiveTransition(Management_ReceiveFSMContext& context, SetAuthority msg);
        void ReceiveTransition(Management_ReceiveFSMContext& context, Shutdown msg);
        void ReceiveTransition(Management_ReceiveFSMContext& context, ClearEmergency msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(Management_ReceiveFSMContext& context, QueryStatus msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(Management_ReceiveFSMContext& context, RequestControl msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(Management_ReceiveFSMContext& context, SetEmergency msg, Receive::Body::ReceiveRec transportData);
        void TimeoutTransition(Management_ReceiveFSMContext& context);
    };

    class Management_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Standby :
        public Management_ReceiveFSM_SM_Default
    {
    public:
        Management_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Standby(const char *name, int stateId)
        : Management_ReceiveFSM_SM_Default(name, stateId)
        {};

        void FailureTransition(Management_ReceiveFSMContext& context);
        void InternalStateChange_To_Management_ReceiveFSM_ReceivingTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_ReadyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_EmergencyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_ReadyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlledTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateATransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_EmergencyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_FailureTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_InitTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_ShutdownTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_StandbyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void ReceiveTransition(Management_ReceiveFSMContext& context, QueryStatus msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(Management_ReceiveFSMContext& context, Reset msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(Management_ReceiveFSMContext& context, Resume msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(Management_ReceiveFSMContext& context, SetEmergency msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(Management_ReceiveFSMContext& context, Shutdown msg, Receive::Body::ReceiveRec transportData);
    };

    class Management_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Ready :
        public Management_ReceiveFSM_SM_Default
    {
    public:
        Management_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Ready(const char *name, int stateId)
        : Management_ReceiveFSM_SM_Default(name, stateId)
        {};

        void FailureTransition(Management_ReceiveFSMContext& context);
        void InternalStateChange_To_Management_ReceiveFSM_ReceivingTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_ReadyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_ControlledTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateBTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_EmergencyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_StandbyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlledTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateATransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_EmergencyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_FailureTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_InitTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_ShutdownTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_StandbyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void ReceiveTransition(Management_ReceiveFSMContext& context, QueryStatus msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(Management_ReceiveFSMContext& context, Reset msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(Management_ReceiveFSMContext& context, SetEmergency msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(Management_ReceiveFSMContext& context, Shutdown msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(Management_ReceiveFSMContext& context, Standby msg, Receive::Body::ReceiveRec transportData);
    };

    class Management_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Emergency :
        public Management_ReceiveFSM_SM_Default
    {
    public:
        Management_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Emergency(const char *name, int stateId)
        : Management_ReceiveFSM_SM_Default(name, stateId)
        {};

        void FailureTransition(Management_ReceiveFSMContext& context);
        void InternalStateChange_To_Management_ReceiveFSM_ReceivingTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_ReadyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_ControlledTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateBTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_ReadyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_StandbyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlledTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateATransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_EmergencyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_FailureTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_InitTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_ShutdownTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_StandbyTransition(Management_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void ReceiveTransition(Management_ReceiveFSMContext& context, Reset msg);
        void ReceiveTransition(Management_ReceiveFSMContext& context, SetAuthority msg);
        void ReceiveTransition(Management_ReceiveFSMContext& context, Shutdown msg);
        void ReceiveTransition(Management_ReceiveFSMContext& context, ClearEmergency msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(Management_ReceiveFSMContext& context, QueryStatus msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(Management_ReceiveFSMContext& context, ReleaseControl msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(Management_ReceiveFSMContext& context, RequestControl msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(Management_ReceiveFSMContext& context, Reset msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(Management_ReceiveFSMContext& context, SetEmergency msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(Management_ReceiveFSMContext& context, Shutdown msg, Receive::Body::ReceiveRec transportData);
        void TimeoutTransition(Management_ReceiveFSMContext& context);
    };

    class Management_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE :
        public Management_ReceiveFSM_SM_Default
    {
    public:
        Management_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE(const char *name, int stateId)
        : Management_ReceiveFSM_SM_Default(name, stateId)
        {};

        void BroadcastGlobalTransition(Management_ReceiveFSMContext& context);
        void BroadcastLocalTransition(Management_ReceiveFSMContext& context);
        void CancelEventTransition(Management_ReceiveFSMContext& context);
        void ClearEmergencyTransition(Management_ReceiveFSMContext& context);
        void CreateEventTransition(Management_ReceiveFSMContext& context);
        void EventErrorTransition(Management_ReceiveFSMContext& context);
        void EventOccurredTransition(Management_ReceiveFSMContext& context);
        void FailureTransition(Management_ReceiveFSMContext& context);
        void InitializedTransition(Management_ReceiveFSMContext& context);
        void QueryAuthorityTransition(Management_ReceiveFSMContext& context);
        void QueryControlTransition(Management_ReceiveFSMContext& context);
        void QueryEventsTransition(Management_ReceiveFSMContext& context);
        void QueryStatusTransition(Management_ReceiveFSMContext& context);
        void QueryTimeoutTransition(Management_ReceiveFSMContext& context);
        void ReceiveTransition(Management_ReceiveFSMContext& context);
        void ReleaseControlTransition(Management_ReceiveFSMContext& context);
        void RequestControlTransition(Management_ReceiveFSMContext& context);
        void ResetTransition(Management_ReceiveFSMContext& context);
        void ResumeTransition(Management_ReceiveFSMContext& context);
        void SendTransition(Management_ReceiveFSMContext& context);
        void SetAuthorityTransition(Management_ReceiveFSMContext& context);
        void SetEmergencyTransition(Management_ReceiveFSMContext& context);
        void ShutdownTransition(Management_ReceiveFSMContext& context);
        void StandbyTransition(Management_ReceiveFSMContext& context);
        void TimeoutTransition(Management_ReceiveFSMContext& context);
        void UpdateEventTransition(Management_ReceiveFSMContext& context);
    };

    class Management_ReceiveFSMContext :
        public statemap::FSMContext
    {
    public:

        Management_ReceiveFSMContext(Management_ReceiveFSM& owner)
        : FSMContext(Management_ReceiveFSM_SM::Receiving_Ready_NotControlled_StateA_Init),
          _owner(owner)
        {};

        Management_ReceiveFSMContext(Management_ReceiveFSM& owner, const statemap::State& state)
        : FSMContext(state),
          _owner(owner)
        {};

        virtual void enterStartState()
        {
            getState().Entry(*this);
            return;
        }

        Management_ReceiveFSM& getOwner() const
        {
            return (_owner);
        };

        Management_ReceiveFSMState& getState() const
        {
            if (_state == NULL)
            {
                throw statemap::StateUndefinedException();
            }

            return (dynamic_cast<Management_ReceiveFSMState&>(*_state));
        };

        void BroadcastGlobalTransition()
        {
            setTransition("BroadcastGlobalTransition");
            (getState()).BroadcastGlobalTransition(*this);
            setTransition(NULL);
        };

        void BroadcastLocalTransition()
        {
            setTransition("BroadcastLocalTransition");
            (getState()).BroadcastLocalTransition(*this);
            setTransition(NULL);
        };

        void CancelEventTransition()
        {
            setTransition("CancelEventTransition");
            (getState()).CancelEventTransition(*this);
            setTransition(NULL);
        };

        void ClearEmergencyTransition()
        {
            setTransition("ClearEmergencyTransition");
            (getState()).ClearEmergencyTransition(*this);
            setTransition(NULL);
        };

        void CreateEventTransition()
        {
            setTransition("CreateEventTransition");
            (getState()).CreateEventTransition(*this);
            setTransition(NULL);
        };

        void EventErrorTransition()
        {
            setTransition("EventErrorTransition");
            (getState()).EventErrorTransition(*this);
            setTransition(NULL);
        };

        void EventOccurredTransition()
        {
            setTransition("EventOccurredTransition");
            (getState()).EventOccurredTransition(*this);
            setTransition(NULL);
        };

        void FailureTransition()
        {
            setTransition("FailureTransition");
            (getState()).FailureTransition(*this);
            setTransition(NULL);
        };

        void InitializedTransition()
        {
            setTransition("InitializedTransition");
            (getState()).InitializedTransition(*this);
            setTransition(NULL);
        };

        void InternalStateChange_To_Management_ReceiveFSM_ReceivingTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_Management_ReceiveFSM_ReceivingTransition");
            (getState()).InternalStateChange_To_Management_ReceiveFSM_ReceivingTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_Management_ReceiveFSM_Receiving_ReadyTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_Management_ReceiveFSM_Receiving_ReadyTransition");
            (getState()).InternalStateChange_To_Management_ReceiveFSM_Receiving_ReadyTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_ControlledTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_ControlledTransition");
            (getState()).InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_ControlledTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateBTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateBTransition");
            (getState()).InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateBTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_EmergencyTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_EmergencyTransition");
            (getState()).InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_EmergencyTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_ReadyTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_ReadyTransition");
            (getState()).InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_ReadyTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_StandbyTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_StandbyTransition");
            (getState()).InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_Controlled_StateB_StandbyTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlledTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlledTransition");
            (getState()).InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlledTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateATransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateATransition");
            (getState()).InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateATransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_EmergencyTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_EmergencyTransition");
            (getState()).InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_EmergencyTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_FailureTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_FailureTransition");
            (getState()).InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_FailureTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_InitTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_InitTransition");
            (getState()).InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_InitTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_ShutdownTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_ShutdownTransition");
            (getState()).InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_ShutdownTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_StandbyTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_StandbyTransition");
            (getState()).InternalStateChange_To_Management_ReceiveFSM_Receiving_Ready_NotControlled_StateA_StandbyTransition(*this, ie);
            setTransition(NULL);
        };

        void QueryAuthorityTransition()
        {
            setTransition("QueryAuthorityTransition");
            (getState()).QueryAuthorityTransition(*this);
            setTransition(NULL);
        };

        void QueryControlTransition()
        {
            setTransition("QueryControlTransition");
            (getState()).QueryControlTransition(*this);
            setTransition(NULL);
        };

        void QueryEventsTransition()
        {
            setTransition("QueryEventsTransition");
            (getState()).QueryEventsTransition(*this);
            setTransition(NULL);
        };

        void QueryStatusTransition()
        {
            setTransition("QueryStatusTransition");
            (getState()).QueryStatusTransition(*this);
            setTransition(NULL);
        };

        void QueryTimeoutTransition()
        {
            setTransition("QueryTimeoutTransition");
            (getState()).QueryTimeoutTransition(*this);
            setTransition(NULL);
        };

        void ReceiveTransition()
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this);
            setTransition(NULL);
        };

        void ReceiveTransition(Reset msg)
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this, msg);
            setTransition(NULL);
        };

        void ReceiveTransition(SetAuthority msg)
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this, msg);
            setTransition(NULL);
        };

        void ReceiveTransition(Shutdown msg)
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this, msg);
            setTransition(NULL);
        };

        void ReceiveTransition(ClearEmergency msg, Receive::Body::ReceiveRec transportData)
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this, msg, transportData);
            setTransition(NULL);
        };

        void ReceiveTransition(QueryStatus msg, Receive::Body::ReceiveRec transportData)
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this, msg, transportData);
            setTransition(NULL);
        };

        void ReceiveTransition(ReleaseControl msg, Receive::Body::ReceiveRec transportData)
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this, msg, transportData);
            setTransition(NULL);
        };

        void ReceiveTransition(RequestControl msg, Receive::Body::ReceiveRec transportData)
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this, msg, transportData);
            setTransition(NULL);
        };

        void ReceiveTransition(Reset msg, Receive::Body::ReceiveRec transportData)
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this, msg, transportData);
            setTransition(NULL);
        };

        void ReceiveTransition(Resume msg, Receive::Body::ReceiveRec transportData)
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this, msg, transportData);
            setTransition(NULL);
        };

        void ReceiveTransition(SetEmergency msg, Receive::Body::ReceiveRec transportData)
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this, msg, transportData);
            setTransition(NULL);
        };

        void ReceiveTransition(Shutdown msg, Receive::Body::ReceiveRec transportData)
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this, msg, transportData);
            setTransition(NULL);
        };

        void ReceiveTransition(Standby msg, Receive::Body::ReceiveRec transportData)
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this, msg, transportData);
            setTransition(NULL);
        };

        void ReleaseControlTransition()
        {
            setTransition("ReleaseControlTransition");
            (getState()).ReleaseControlTransition(*this);
            setTransition(NULL);
        };

        void RequestControlTransition()
        {
            setTransition("RequestControlTransition");
            (getState()).RequestControlTransition(*this);
            setTransition(NULL);
        };

        void ResetTransition()
        {
            setTransition("ResetTransition");
            (getState()).ResetTransition(*this);
            setTransition(NULL);
        };

        void ResumeTransition()
        {
            setTransition("ResumeTransition");
            (getState()).ResumeTransition(*this);
            setTransition(NULL);
        };

        void SendTransition()
        {
            setTransition("SendTransition");
            (getState()).SendTransition(*this);
            setTransition(NULL);
        };

        void SetAuthorityTransition()
        {
            setTransition("SetAuthorityTransition");
            (getState()).SetAuthorityTransition(*this);
            setTransition(NULL);
        };

        void SetEmergencyTransition()
        {
            setTransition("SetEmergencyTransition");
            (getState()).SetEmergencyTransition(*this);
            setTransition(NULL);
        };

        void ShutdownTransition()
        {
            setTransition("ShutdownTransition");
            (getState()).ShutdownTransition(*this);
            setTransition(NULL);
        };

        void StandbyTransition()
        {
            setTransition("StandbyTransition");
            (getState()).StandbyTransition(*this);
            setTransition(NULL);
        };

        void TimeoutTransition()
        {
            setTransition("TimeoutTransition");
            (getState()).TimeoutTransition(*this);
            setTransition(NULL);
        };

        void UpdateEventTransition()
        {
            setTransition("UpdateEventTransition");
            (getState()).UpdateEventTransition(*this);
            setTransition(NULL);
        };

    private:

        Management_ReceiveFSM& _owner;
    };
}


/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */

#endif // _H_MANAGEMENT_RECEIVEFSM_SM
